name: PlateMines
version: 3.0.0.1
description: Stops players/Mob from using pressureplates and tripwires, configurable with other options.
author: pyropyro78
main: com.pyromanticgaming.platemines.PlateMines